### ISSUE TITLE
Payment not loading up on frontend Payment Page

### ISSUE THREAD

**Issue by taiwoobe** [PaystackHQ/plugin-prestashop-1.6#10]
Hello,

I am having an issue with the module. It is currently not showing on my frontend on the payments page. Please I would appreciate if you could help look into this. 

The link to the site is https://shop4younow.com.ng/ so you can do a check on.

Thanks

**Comment by steveamaza** [comment]
Hello @taiwoobe what version of Prestashop are you using? You posted this issue both on the 1.6 and the 1.7 version of the plugin

**Comment by taiwoobe** [comment]
Its for 1.6. Apologies I posted on 1.7

**Comment by steveamaza** [comment]
@taiwoobe can you confirm you have activated the plugin? Can I see a screenshot of your settings page?

**Comment by taiwoobe** [comment]
@steveamaza here is a screenshot of the backend settings.
![Capture](https://user-images.githubusercontent.com/9431878/60896025-83e51f00-a25d-11e9-8f3c-af5210623c6b.PNG)

**Comment by steveamaza** [comment]
Hello @taiwoobe for some reason, I'm only just seeing your response. Sincere apologies. I'm going to close this but if the issue persists, please comment so I can reopen
